version: "3.8"

services:
  postgres:
    build: "./postgres"
    image: akhyariz/kudemo-todo-postgres
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  todo-api:
    build: "./api"
    image: akhyariz/kudemo-todo-api
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      POSTGRES_ENABLED: "true"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_DATABASE: "postgres"
      DB_PASSWORD: "postgres"
  todo-ui:
    build: "./ui"
    image: akhyariz/kudemo-todo-ui
    depends_on:
      - todo-api
    ports:
      - 3000:80
